package reex;

import java.util.concurrent.atomic.AtomicLong;

import org.springframework.web.bind.annotation.*;
import org.springframework.stereotype.Controller;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
@Controller //This means that class is a Controller
@RequestMapping(path="/reex") //This means URL's start with /reex

public class ReexController {

    @Autowired // This means to get the bean called clientepermutaRepository
               // which is auto-generated by Spring

    private ClientePermutaRepository clientepermutaRepository;

    /**
    private static final String template = "Hello, %s!";
    private final AtomicLong counter = new AtomicLong();

    @RequestMapping("/greeting")
    public Reex greeting(@RequestParam(value="name", defaultValue="World") String name) {
        return new Reex(counter.incrementAndGet(),
                String.format(template, name));
    }
    **/

    @GetMapping(path="/add") //Map only GET requests
    public @ResponseBody String addNewClientePermuta (@RequestParam String nome,
                                                      @RequestParam String email,
                                                      @RequestParam String celular,
                                                      @RequestParam String otherinfo) {
        //@ResponseBody means the returned String is the response, not a view name
        //@RequestParam means it is a parameter from the GET or POST request

        ClientePermuta cliente = new ClientePermuta();
        cliente.setNome(nome);
        cliente.setEmail(email);
        cliente.setCelular(celular);
        cliente.setOtherinfo(otherinfo);
        clientepermutaRepository.save(cliente);
        return "Gravado";

    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<ClientePermuta> getAllClientesPermuta(){
        //This returns a JSON or XML with all clients
        return clientepermutaRepository.findAll();
    }

}